// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRhlpoyS_rhxdHUFOTldVJqaVk6UHp8Ew',
    appId: '1:259580743014:web:6969dd3648dafe132b8ca7',
    messagingSenderId: '259580743014',
    projectId: 'rumored-95fd4',
    authDomain: 'rumored-95fd4.firebaseapp.com',
    storageBucket: 'rumored-95fd4.appspot.com',
    measurementId: 'G-T6JKKXY106',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfvuzNY59FYyMq_-HcAhQ0ZQx3M_EDJ2I',
    appId: '1:259580743014:android:592bb7ee53f261502b8ca7',
    messagingSenderId: '259580743014',
    projectId: 'rumored-95fd4',
    storageBucket: 'rumored-95fd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXzXRXr6CUv5Z0JNeRE-Fx8wBmLjvoVls',
    appId: '1:259580743014:ios:05de05aefe96b61c2b8ca7',
    messagingSenderId: '259580743014',
    projectId: 'rumored-95fd4',
    storageBucket: 'rumored-95fd4.appspot.com',
    iosBundleId: 'com.example.rumored',
  );
}
